# Site settings
title: Ramansh Sharma blog
email:
description: "Musings of a Computer Science student."
baseurl: '\blog'
url: "http://ramanshsharma2806.github.io/blog"
twitter_username: ramanshsharma1
github_username:  ramanshsharma2806

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
