# Site settings
title: Reissaavedra's Blog
email: reisson.saavedra.miguel@gmail.com
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://reissavedra.github.io"
twitter_username: SaavedraReisson
github_username:  reissavedra

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
